version: '3'
services:
  # open ldap server to test authentication gainst
  # see: https://github.com/rroemhild/docker-test-openldap
  ldap:
    image: rroemhild/test-openldap
    networks: 
      ldapnet: 
        aliases: 
          - hub-test-ldap

  jh-ldap-dev:
    build:
      dockerfile: dev.dockerfile
      context: .
      args: 
        PYTHON_VERSION: 3.6
    depends_on:
      - ldap
    # prevent container from exiting before vs code executes commands in it
    command: /bin/sh -c "while sleep 1000; do :; done"
    # the ldap host for testing
    environment: 
      LDAP_HOST: hub-test-ldap
    volumes:
      # bind mount the project directory for development inside the container
      - .:/workspace:cached
    networks: 
      - ldapnet

networks: 
  ldapnet:
